### ISSUE TITLE
fix(unrdup): make module compile and its tests build against current main

### ISSUE THREAD

**Issue by 3Hren** [yanet-platform/yanet2#2254]
## Motivation

Commit bc3ba5e4 ("feat(unrdup): redistribute balancer ICMP errors to peer balancers") landed on `main` with a functional test that does not compile against the current tree, so every Go CI job on `main` is red: Go Lint ("golangci-lint modernize"), Go race tests, build-asan-test, build-deb, build-release-artifacts. The module was developed against a pre-#2240 tree (`filter.IPNets` still present) and merged without rebasing onto the tree that later removed it, so `main` has been broken since the merge.

## Evidence

Failing job (run 32840126260, job 97777553913, triggered on a PR rebased onto main after the merge):

- `modules/unrdup/tests/functional/unrdup_test.go:113:12: cannot use sink.Free (value of type func() error) as func() value in argument to t.Cleanup`
- `modules/unrdup/tests/functional/unrdup_test.go:133:27: agent.UpdatePlainDevices undefined (type *ffi.Agent has no field or method UpdatePlainDevices)`
- `modules/unrdup/tests/functional/unrdup_test.go:146:20`, `:147:20`, `:153:20`, `:154:20`: `undefined: filter.IPNets` (the type was removed by #2240 / PR b9460b87)

Confirmed reproduced on `origin/main` at 2807b899 (current HEAD): `modules/unrdup/tests/functional/unrdup_test.go` still references `filter.IPNets` and `agent.UpdatePlainDevices`, which do not exist on this tree.

## Scope

- `modules/unrdup/tests/functional/unrdup_test.go`: adapt to the current `forward.NewBackend(...).UpdateModule` cleanup signature, the current `ffi.Agent` device-update API, and the current filter/network-list types (post-#2240).
- Any other `modules/unrdup` code that references removed/renamed APIs.

## Acceptance

- [ ] `go build ./...` and `go vet ./...` succeed for `modules/unrdup` on current `main`.
- [ ] `modules/unrdup` tests build (`go test -run xxx ./modules/unrdup/...` or equivalent compiles).
- [ ] The Go Lint, Go race, build-asan-test, build-deb and build-release-artifacts CI jobs are green on `main` again.

**Comment by 3Hren** [comment]
The breakage is wider than the Go test: `modules/unrdup/api/controlplane.c` also fails to build against the current `cp_module_init` signature (CI job 97777555439: "error: too many arguments to function 'cp_module_init'" and an incompatible pointer type, both at controlplane.c:254/:259), so the fix needs to cover both the C API and the functional test.
